stages:
  split_data:
    cmd: python datasplit.py
    deps:
    - catvdog/raw
    - datasplit.py
    outs:
    - catvdog/test
    - catvdog/train
    - catvdog/val
  train_yolo:
    cmd: python train.py
    deps:
    - catvdog.yaml
    - catvdog/train
    - catvdog/val
    - train.py
    outs:
    - runs/detect/train/weights/best.pt
    metrics:
    - runs/detect/train/results.csv:
        cache: false
    plots:
    - runs/detect/train/confusion_matrix.png:
        cache: false
    - runs/detect/train/results.png:
        cache: false
