name: MLOps CI Pipeline

on: [push] # This tells GitHub to run this every time you push code

jobs:
  test-model-and-api:
    runs-on: self-hosted # Use self-hosted runner to access your local environment and files
    
    steps:
      - name: 1. Checkout Repository
        uses: actions/checkout@v3

      - name: 2. Check Python Version
        run: C:\Users\1003380\AppData\Local\anaconda3\envs\ultralytics\python.exe --version

      - name: 3. Test API Loading
        # A quick command to make sure your FastAPI code doesn't have syntax errors
        run: C:\Users\1003380\AppData\Local\anaconda3\envs\ultralytics\python.exe -c "from utils.fastAPI import app; print('FastAPI App Loaded Successfully!')"

      - name: 4. Sync dvc
        # Check if the data loading script runs without errors
        run: |
          C:\Users\1003380\AppData\Local\anaconda3\envs\ultralytics\Scripts\dvc.exe cache dir C:\Users\1003380\Mine\MLOps\.dvc\cache
          C:\Users\1003380\AppData\Local\anaconda3\envs\ultralytics\Scripts\dvc.exe config cache.type copy
          C:\Users\1003380\AppData\Local\anaconda3\envs\ultralytics\Scripts\dvc.exe checkout
      - name: 5. Model Check
        # Verify the YOLO model actually loads and initializes without crashing
        run: C:\Users\1003380\AppData\Local\anaconda3\envs\ultralytics\python.exe -c "from ultralytics import YOLO; model = YOLO('runs/detect/train/weights/best.pt'); print('YOLO Model Initialized Successfully!')"

      - name: 6. Gatekeeper check
        # This is a place to check if the current model scores higher than the previous one before deploying
        run: C:\Users\1003380\AppData\Local\anaconda3\envs\ultralytics\python.exe utils/gatekeeper.py

      - name: 7. Continuous Deployment (CD)
        run: |
          $status = Get-Content "deployment_status.txt"
          New-Item -ItemType Directory -Force -Path "C:\Shadow_Pipeline_Production"
          
          if ($status -eq "DEPLOY_MODEL") {
              Write-Host "Deploying new Model, API, and High Score to Production..."
              Copy-Item -Path "runs\detect\train\weights\best.pt" -Destination "C:\Shadow_Pipeline_Production\best.pt" -Force
              Copy-Item -Path "utils" -Destination "C:\Shadow_Pipeline_Production\utils" -Recurse -Force
              Copy-Item -Path "new_high_score.txt" -Destination "C:\Shadow_Pipeline_Production\best_map.txt" -Force
          }
          elseif ($status -eq "DEPLOY_CODE") {
              Write-Host "Deploying API Code updates only. Model remains untouched..."
              Copy-Item -Path "utils" -Destination "C:\Shadow_Pipeline_Production\utils" -Recurse -Force
          }